apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init-topics
  namespace: pipeline
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: apache/kafka:3.7.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -e
              echo "Waiting Kafka..."
              sleep 5
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic raw.student.csv --partitions 1 --replication-factor 1
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic raw.student.http --partitions 1 --replication-factor 1
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic output-topic --partitions 1 --replication-factor 1
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic output-topic-dlq --partitions 1 --replication-factor 1
              echo "Kafka topics ready."
