apiVersion: v1
kind: Pod
metadata:
  name: csv-uploader
  namespace: pipeline
spec:
  restartPolicy: Never
  containers:
    - name: uploader
      image: python:3.11-alpine
      imagePullPolicy: IfNotPresent
      command: ["sh","-lc","sleep 36000"]
      volumeMounts:
        - name: csv
          mountPath: /data
  volumes:
    - name: csv
      persistentVolumeClaim:
        claimName: csv-pvc
